apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: red-hat-test
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: nginx-simple
data:
  nginx.conf: |
    worker_processes  auto;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      sendfile      on;
      access_log    /dev/stdout;
      error_log     /dev/stderr;

      server {
        listen       8080;
        server_name  _;

        location = /healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }

        location / {
          root   /usr/share/nginx/html;
          index  index.html;
          try_files $uri $uri/ =404;
        }
      }
    }
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8"/>
      <title>OpenShift NGINX</title>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <style>
        body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem;line-height:1.4}
        .card{max-width:680px;padding:1.25rem;border:1px solid #e5e7eb;border-radius:12px}
        code{background:#f3f4f6;padding:.2rem .4rem;border-radius:6px}
      </style>
    </head>
    <body>
      <div class="card">
        <h1>✅ NGINX on OpenShift</h1>
        <p>If you can read this, the deployment works.</p>
        <p>Health check: <code>/healthz</code></p>
      </div>
    </body>
    </html>
